---
abstract: 'Perl module to parse the webalizer.hist-file.'
author:
  - 'Yoran Heling <yorhel@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Webalizer-Hist
provides:
  Webalizer::Hist:
    file: lib/Webalizer/Hist.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
